return {
	{
		"xiyaowong/transparent.nvim",
		lazy = false,
		priority = 1000,
		opts = {
			groups = {
				"Normal",
				"NormalNC",
				"Comment",
				"Constant",
				"Special",
				"Identifier",
				"Statement",
				"PreProc",
				"Type",
				"Underlined",
				"Todo",
				"String",
				"Function",
				"Conditional",
				"Repeat",
				"Operator",
				"Structure",
				"LineNr",
				"NonText",
				"SignColumn",
				"CursorLineNr",
				"EndOfBuffer",
			},
			extra_groups = {
				"NormalFloat",
				"NvimTreeNormal",
				"NvimTreeNormalNC",
				"TelescopeNormal",
				"TelescopeBorder",
				"TelescopePromptNormal",
				"TelescopePromptBorder",
				"TelescopeResultsNormal",
				"TelescopePreviewNormal",
				"LazyNormal",
				"MasonNormal",
				"FloatBorder",
				"WhichKeyFloat",
				"LspInfoBorder",
				"LspSignatureActiveParameter",
				"CmpItemAbbr",
				"CmpItemAbbrDeprecated",
				"CmpItemAbbrMatch",
				"CmpItemAbbrMatchFuzzy",
				"CmpItemMenu",
				"CmpDocumentation",
				"CmpDocumentationBorder",
			},
			exclude_groups = {},
		},
	},
}
