return {
	"folke/which-key.nvim",
	event = "VeryLazy",
	opts = {
		preset = "helix",
		delay = 300,
		expand = 1,
		notify = false,
		triggers = {
			{ "<auto>", mode = "nixsotc" },
			{ "s", mode = { "n", "v" } },
		},
		spec = {
			{
				mode = { "n", "v" },
				{ "<leader>b", group = "buffer" },
				{ "<leader>c", group = "code" },
				{ "<leader>f", group = "file/find" },
				{ "<leader>g", group = "git" },
				{ "<leader>gh", group = "hunks" },
				{ "<leader>q", group = "quit/session" },
				{ "<leader>s", group = "search" },
				{ "<leader>u", group = "ui/toggle" },
				{ "<leader>x", group = "diagnostics/quickfix" },
				{ "<leader>n", group = "next/previous" },
				{ "<leader>p", group = "previous" },
				{ "<leader>r", group = "replace" },
				{ "<leader>t", group = "toggle/terminal" },
				{ "g", group = "goto" },
				{ "gs", group = "surround" },
				{ "z", group = "fold" },
				{ "]", group = "next" },
				{ "[", group = "prev" },
				-- { "<leader><tab>", group = "tabs" },
			},
		},
		win = {
			border = "rounded",
			padding = { 1, 2 },
			title = true,
			title_pos = "center",
			zindex = 1000,
			bo = {},
			wo = {
				winblend = 10,
			},
		},
		layout = {
			width = { min = 20 },
			spacing = 3,
		},
		keys = {
			scroll_down = "<c-d>",
			scroll_up = "<c-u>",
		},
		sort = { "local", "order", "group", "alphanum", "mod" },
		replace = {
			key = {
				function(key)
					return require("which-key.view").format(key)
				end,
				-- { "<Space>", "SPC" },
				-- { "<CR>", "RET" },
				-- { "<Tab>", "TAB" },
			},
			desc = {
				{ "<Plug>%(.*)$", "%1" },
				{ "^%+", "" },
				{ "<[cC]md>", "" },
				{ "<[cC][rR]>", "" },
				{ "<[sS]ilent>", "" },
				{ "^lua%s+", "" },
				{ "^call%s+", "" },
				{ "^:%s*", "" },
			},
		},
		icons = {
			breadcrumb = "»",
			separator = "➜",
			group = "+",
			ellipsis = "…",
			mappings = true,
			rules = {},
			colors = true,
			keys = {
				Up = " ",
				Down = " ",
				Left = " ",
				Right = " ",
				C = "󰘴 ",
				M = "󰘵 ",
				D = "󰘳 ",
				S = "󰘶 ",
				CR = "󰌑 ",
				Esc = "󱊷 ",
				ScrollWheelDown = "󱕐 ",
				ScrollWheelUp = "󱕑 ",
				NL = "󰌑 ",
				BS = "󰁮",
				Space = "󱁐 ",
				Tab = "󰌒 ",
				F1 = "󱊫",
				F2 = "󱊬",
				F3 = "󱊭",
				F4 = "󱊮",
				F5 = "󱊯",
				F6 = "󱊰",
				F7 = "󱊱",
				F8 = "󱊲",
				F9 = "󱊳",
				F10 = "󱊴",
				F11 = "󱊵",
				F12 = "󱊶",
			},
		},
		show_help = true,
		show_keys = true,
		disable = {
			buftypes = {},
			filetypes = {},
		},
	},
}
